# Generated by Django 3.1.6 on 2022-03-14 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, max_length=256, unique=True, verbose_name='Url resource')),
            ],
            options={
                'verbose_name': 'Url resource',
                'verbose_name_plural': 'Urls resource',
            },
        ),
        migrations.CreateModel(
            name='ApplicationProcessing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='Datetime')),
                ('task_id', models.BigIntegerField(blank=True, null=True, verbose_name='Task id')),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Data loading'), (2, 'In progress'), (3, 'Finish')], null=True, verbose_name='Status')),
                ('finished_file', models.FileField(blank=True, db_index=True, null=True, upload_to='documents/pdf', verbose_name='Finished file pdf')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('user_url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web_generator.urlresource', verbose_name='Url resource for generate')),
            ],
            options={
                'verbose_name': 'Application processing to pdf',
                'verbose_name_plural': 'Application processing to pdf',
            },
        ),
    ]
