# Generated by Django 3.1.6 on 2022-03-14 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationprocessing',
            name='task_id',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Task id'),
        ),
    ]
