# Generated by Django 3.1.6 on 2022-03-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_generator', '0002_auto_20220314_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationprocessing',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Status'),
        ),
    ]
